Auth0: Migrate Rules to Actions
cloudnativedaysjp/terraform pull request #134
Opened 2024-03-31 13:05 UTC by hrk091

Auth0 RulesをActionsにマイグレーションしました。
今でも要るのか怪しいものもありますが、一旦全てActions化しています。

Extension系（AccountLink、Authorization）が実装が多少ややこしく、正しく動くか怪しいです。
他はほぼ機械的な変換だけなので、おそらく動くと思います。

ポイントはコードの各行にコメントします。

2024-03-31 13:14 UTC, hrk091 commented on auth0/actions.tf
> +  filename = "actions/addRoleToIdToken.js"
inlineで書くとIaC上でのedit/reviewがしにくいので、別ファイルに分けています。

2024-03-31 13:14 UTC, hrk091 commented on auth0/actions.tf
> +  dependencies {
依存ライブラリとsecretが、各actionsリソースに個別に定義できるようになっています。

2024-03-31 13:14 UTC, hrk091 commented on auth0/actions/auth0AccountLinkExtension.js
> +// Copied from https://github.com/auth0-extensions/auth0-account-link-extension/issues/165#issuecomment-1753005657
公式のGitHubはもうメンテされていないですが、issueで有志がAction対応版を貼ってくれていて、パット見動きそうなので、それを使っています。
libraryは、そこで指定されているversionを使っています。

2024-03-31 13:14 UTC, hrk091 commented on auth0/actions/auth0AuthorizationExtension.js
> +  // set as custom claim for authorization by groups at ArgoCD
idTokenにgroups custom claimを付与するruleがArgoCD用として定義されていましたが、Authorization Extensionの中でcustom claim追加までやってしまっています。理由は以下です。
- ActionsはRulesとは違ってcommon contextがなく、Actionsをまたいだ値の参照がやりにくい
- groups custom claimの追加はArgoCD専用のものではなく他でも使えるものなので、そもそもArgoCD用として定義されていることが変

このため、ArgoCD用のRulesに対応するActionsは存在しません。

2024-03-31 13:14 UTC, hrk091 commented on auth0/actions.tf
> +# data "local_file" "saml_attributes_mapping_handler" {
SAMLAttributeMappingは、Ruleとして登録されていますがdisabledな状態です。
一応コードとしては移行しつつ、こちらでもリソースを作らない状態にしています。

2024-03-31 13:17 UTC, hrk091 commented on auth0/actions.tf
> +    value = "TODO"
auth0_clientのsecretなどはdata参照で渡したのですが、このsecretだけは別途渡す必要があります。
Terraform Cloudにcredentialを保存してterraform実行時にinjectする機能ってあったりしますか？
あればそれを使うたいのですが、なかったらAWS SecretsManagerあたりを使おうかと思います。

2024-03-31 13:20 UTC, hrk091 commented
とりあえず、RulesをひととおりActions化しました。
動作検証がまったくできていないので、Approveいただけたら、Rulesを残して併用する状態で一つずつ投入し、それぞれ動作確認しようと思います。

1点、Authorization ExtensionのところのAPI_KEYをどこから入れるかだけ、Terraform Cloudに良い機能があれば教えてほしいです！

2024-03-31 13:22 UTC, hrk091 commented
なお、マイグレーションの大筋の方針はこのドキュメントにまとまっていて原則この記述に従っているので、review前にざっと流し読みしていただけると良いかもです！
https://auth0.com/docs/customize/actions/migrate/migrate-from-rules-to-actions

2024-04-09 01:11 UTC, jacopen requested changes

2024-04-09 01:11 UTC, jacopen commented on auth0/actions.tf
> +    value = "TODO"
可能です！

2024-04-09 01:11 UTC, jacopen commented on auth0/actions.tf
> +    value = "TODO"
```suggestion
    value = var.authz_ext_api_key
```

の変更を入れて、別の場所に

```
variable "authz_ext_api_key" {}
```

を宣言しておいてください。
あとはauthz_ext_api_keyの実体をTerraformCloud側に入れればOKです

2024-04-21 01:57 UTC, hrk091 commented
@jacopen terraform cloudからsecret injectionするようにして、CI通しました！

2024-04-21 01:57 UTC, hrk091 commented
順番に検証やっていきます。

2024-04-27 11:39 UTC, hrk091 reviewed
ruleとactionsで共存できない箇所が一部あるので、rule -> actionsへの切り替えは一気にやります。以下の流れでやります。

- このPRをmerge -> terraform applyされる
- タイミングをあわせて、ruleの方をUI上でdisableする
- 動作確認する
- 大丈夫なら、ruleを消すPRを作る

2024-04-27 11:39 UTC, hrk091 commented on auth0/actions.tf
> +    name    = "querystring"
とても古いので流石に最新化しようと思ったのですが、最新はESModule限定でCommonJS環境だと使えないようだったので、GitHub issueで指定されているものに戻しました。

2024-04-27 11:39 UTC, hrk091 commented on auth0/actions/auth0AuthorizationExtension.js
> +  api.user.setUserMetadata('groups', res.data.groups);
元々、後段のactionsへのgroupsの伝搬にもid_tokenを使っていましたが、actionsのpost-login flowではそれができなくなりました（id_tokenへのinjectは指定できますが、まだ未生成のため引き出せません）。このため、user_metadataを使うように変えました。

2024-04-27 11:39 UTC, hrk091 commented on auth0/actions/auth0AccountLinkExtension.js
> +    const secondaryUser = await apiCall({
ここのsecondaryUserは、一度Account統合されると取得できなくなるので、ruleとactionsを共存させられません。

2024-05-06 04:50 UTC, jacopen approved these changes
LGTM!

2024-05-06 06:23 UTC, merged